config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root 'home#index'

  resources :authors

  namespace :api do
    namespace :v1 do
      defaults format: :json do
        resources :posts, except: [:new, :edit]
      end
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :author
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  validates :name, :surname, presence: true
  has_many :posts, dependent: :destroy
  has_one :address, dependent: :destroy
  has_many :comments, as: :commentable

  before_create :default_age

  enum status: [:active, :retired]

  scope :old, -> { where('age > 30') }

  def fullname
    "#{name} #{surname}"
  end

  def self.delete_old_authors
    Author.old.destroy_all
  end

  private

  def default_age
    self.age = 25 unless age
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
end

app/models/following.rb
class Following < ApplicationRecord
  belongs_to :followed_user, class_name: 'User', foreign_key: 'follower_id'
  belongs_to :followee, class_name: 'User', foreign_key: 'followee_id'
end

app/models/paragraph.rb
class Paragraph < ApplicationRecord
  belongs_to :section
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author
  has_many :ratings
  has_many :users, through: :ratings

  has_many :sections
  has_many :paragraphs, through: :sections

  has_many :comments, as: :commentable

  validates :title, :content, presence: true
  validates :title, length: { maximum: 80 }
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :post
  has_many :paragraphs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook]

  has_many :ratings
  has_many :posts, through: :ratings

  has_many :followed_followings, class_name: 'Following', foreign_key: 'followee_id'
  has_many :followed_users, through: :followed_followings, class_name: 'User', foreign_key: 'followee_id'

  has_many :follower_followings, class_name: 'Following', foreign_key: 'follower_id'
  has_many :followees, through: :follower_followings, class_name: 'User', foreign_key: 'follower_id'

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApiController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    return render json: { errors: @post.errors.full_messages }, status: :unprocessable_entity unless @post.save

    render 'show', status: :created
  end

  def update
    @post = Post.find(params[:id])
    unless @post.update(post_params)
      return render json: { errors: @post.errors.full_messages }, status: :unprocessable_entity
    end

    render 'show'
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    head :no_content
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :author_id)
  end
end

app/controllers/api_controller.rb
class ApiController < ActionController::API
  before_action :authenticate_user!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      redirect_to @author, notice: 'Author created'
    else
      render :new
    end
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])
    if @author.update(author_params)
      redirect_to @author, notice: 'Author updated'
    else
      render :edit
    end
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy
    redirect_to authors_path, notice: 'Author destroyed'
  end

  private

  def author_params
    params.require(:author).permit(:name, :surname, :age)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      if is_navigational_format?
        set_flash_message(
          :notice,
          :success,
          kind: 'Facebook'
        )
      end
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path, alert: 'Facebook login failed'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/_form.erb
<% if @author.errors.any? %>
  <ul>
    <% @author.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @author do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :surname %>
  <%= f.text_field :surname %>
  <%= f.label :age %>
  <%= f.text_field :age %>
  </hr>
  <%= f.submit 'Submit' %>
<% end %>

app/views/authors/edit.html.erb
<h1>Edit author</h1>
<%= render 'form' %>

app/views/authors/index.html.erb
<h1>List of authors</h1>

<ul>
  <% @authors.each do |author| %>
    <li>
      <%= link_to author.fullname, author %>
      <-||->
      <%= link_to 'Edit', edit_author_path(author) %>
      <-||->
      <%= link_to 'Delete', author, method: :delete, data: { confirm: 'Sure?' } %>
    </li>
  <% end %>
</ul>

<%= link_to 'Home', root_url %>
<%= link_to 'New author', new_author_path %>

app/views/authors/new.html.erb
<h1>Add new author</h1>
<%= render 'form' %>

app/views/authors/show.html.erb
<h1>Author page</h1>
<h2><%= @author.fullname %></h2>
<h3>Age: <%= @author.age %></h3>

<%= link_to 'Back to list of authors', authors_path %>

app/views/home/index.html.erb
<h1>Hello Blog</h1>

<%= link_to 'Authors', authors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Internblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/partials/navbar' %>
    <%= render 'layouts/partials/flash' %>

    <%= yield %>
  </body>
</html>

app/views/layouts/partials/_flash.erb
<%= alert if alert %>
<%= notice if notice %>

app/views/layouts/partials/_navbar.erb
<% if current_user %>
  <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to 'Log in', new_user_session_path %>
  <%= link_to 'Register', new_user_registration_path %>
  <%= link_to 'Log in with facebook', user_facebook_omniauth_authorize_path %>
<% end %>